name: "Update README.md"

on:
  schedule:
    - cron: "0 03 * * *"
  workflow_dispatch:

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install NodeJS packages
        run: |
          npm install

    #   - name: Run updater.py
    #     env:
    #       HEADERS: ${{ secrets.HEADERS }}
    #     run: |
    #       python updater.py
      - name: Run generate.js
        env:
          HEADERS: ${{ secrets.HEADERS }}
        run: |
          node generate.js

      - name: Commit and push if changed
        run: |
          git config user.name "Yuuka Chan"
          git config user.email "kiizuha@gnuweeb.org"
          git diff
          git add README.md
          git commit -m "update some magic in README.md"
          git push
